{"judul": "Romeo + Juliet", "genre": ["Drama", "Romance", "1 November 1996 (USA)\n"], "bintang": ["Baz Luhrmann", "William Shakespeare", "Craig Pearce", "1 more credit", "Leonardo DiCaprio", "Claire Danes", "John Leguizamo", "See full cast & crew"], "certificate": "PG-13", "storyline": "Shakespeare's famous play is updated to the hip modern suburb of Verona still retaining its original dialogue."}
{"judul": "The Perks of Being a Wallflower", "genre": ["Drama", "Romance", "12 October 2012 (USA)\n"], "bintang": ["Stephen Chbosky", "Stephen Chbosky", "Stephen Chbosky", "Logan Lerman", "Emma Watson", "Ezra Miller", "See full cast & crew"], "certificate": "PG-13", "storyline": "An introvert freshman is taken under the wings of two seniors who welcome him to the real world."}
{"judul": "The Maze Runner", "genre": ["Action", "Mystery", "Sci-Fi", "19 September 2014 (USA)\n"], "bintang": ["Wes Ball", "Noah Oppenheim", "Grant Pierce Myers", "2 more credits", "Dylan O'Brien", "Kaya Scodelario", "Will Poulter", "See full cast & crew"], "certificate": "PG-13", "storyline": "Thomas is deposited in a community of boys after his memory is erased, soon learning they're all trapped in a maze that will require him to join forces with fellow \"runners\" for a shot at escape."}
{"judul": "The New Mutants", "genre": ["Action", "Horror", "Sci-Fi", "28 August 2020 (USA)\n"], "bintang": ["Josh Boone", "Josh Boone", "Knate Lee", "Maisie Williams", "Anya Taylor-Joy", "Charlie Heaton", "See full cast & crew"], "certificate": "PG-13", "storyline": "Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves."}
{"judul": "The Revenant", "genre": ["Action", "Adventure", "Drama", "8 January 2016 (USA)\n"], "bintang": ["Alejandro G. I\u00f1\u00e1rritu", "Mark L. Smith", "Alejandro G. I\u00f1\u00e1rritu", "1 more credit", "Leonardo DiCaprio", "Tom Hardy", "Will Poulter", "See full cast & crew"], "certificate": "R", "storyline": "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team."}
{"judul": "Logan", "genre": ["Action", "Drama", "Sci-Fi", "3 March 2017 (USA)\n"], "bintang": ["James Mangold", "James Mangold", "Scott Frank", "2 more credits", "Hugh Jackman", "Patrick Stewart", "Dafne Keen", "See full cast & crew"], "certificate": "R", "storyline": "In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety."}
{"judul": "Love Actually", "genre": ["Comedy", "Drama", "Romance", "14 November 2003 (USA)\n"], "bintang": ["Richard Curtis", "Richard Curtis", "Hugh Grant", "Martine McCutcheon", "Liam Neeson", "See full cast & crew"], "certificate": "R", "storyline": "Follows the lives of eight very different couples in dealing with their love lives in various loosely interrelated tales all set during a frantic month before Christmas in London, England."}
{"judul": "Mayans M.C.            ", "genre": ["Crime", "Drama", "Thriller", "TV Series (2018\u2013 )\n"], "bintang": ["Elgin James", "Kurt Sutter", "JD Pardo", "Clayton Cardenas", "Sarah Bolger", "See full cast & crew"], "certificate": "TV-MA", "storyline": "Set in a post-Jax Teller world, \"Mayans MC\" sees EZ Reyes, a former golden boy now fresh out of prison, as a prospect in the Mayan MC charter on the California-Mexico border who must carve out his new outlaw identity."}
{"judul": "Argo", "genre": ["Biography", "Drama", "Thriller", "12 October 2012 (USA)\n"], "bintang": ["Ben Affleck", "Chris Terrio", "Tony Mendez", "1 more credit", "Ben Affleck", "Bryan Cranston", "John Goodman", "See full cast & crew"], "certificate": "R", "storyline": "Acting under the cover of a Hollywood producer scouting a location for a science fiction film, a CIA agent launches a dangerous operation to rescue six Americans in Tehran during the U.S. hostage crisis in Iran in 1979."}
{"judul": "Star Wars: Episode IV - A New Hope", "genre": ["Action", "Adventure", "Fantasy", "25 May 1977 (USA)\n"], "bintang": ["George Lucas", "George Lucas", "Mark Hamill", "Harrison Ford", "Carrie Fisher", "See full cast & crew"], "certificate": "PG", "storyline": "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader."}
{"judul": "The Shape of Water", "genre": ["Adventure", "Drama", "Fantasy", "22 December 2017 (USA)\n"], "bintang": ["Guillermo del Toro", "Guillermo del Toro", "Vanessa Taylor", "1 more credit", "Sally Hawkins", "Octavia Spencer", "Michael Shannon", "See full cast & crew"], "certificate": "R", "storyline": "At a top secret research facility in the 1960s, a lonely janitor forms a unique relationship with an amphibious creature that is being held in captivity."}
{"judul": "Braveheart", "genre": ["Biography", "Drama", "History", "24 May 1995 (USA)\n"], "bintang": ["Mel Gibson", "Randall Wallace", "Mel Gibson", "Sophie Marceau", "Patrick McGoohan", "See full cast & crew"], "certificate": "R", "storyline": "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England."}
{"judul": "Hidden Figures", "genre": ["Biography", "Drama", "History", "6 January 2017 (USA)\n"], "bintang": ["Theodore Melfi", "Allison Schroeder", "Theodore Melfi", "1 more credit", "Taraji P. Henson", "Octavia Spencer", "Janelle Mon\u00e1e", "See full cast & crew"], "certificate": "PG", "storyline": "The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program."}
{"judul": "X-Men: Days of Future Past", "genre": ["Action", "Adventure", "Sci-Fi", "23 May 2014 (USA)\n"], "bintang": ["Bryan Singer", "Simon Kinberg", "Jane Goldman", "2 more credits", "Patrick Stewart", "Ian McKellen", "Hugh Jackman", "See full cast & crew"], "certificate": "PG-13", "storyline": "The X-Men send Wolverine to the past in a desperate effort to change history and prevent an event that results in doom for both humans and mutants."}
{"judul": "Independence Day", "genre": ["Action", "Adventure", "Sci-Fi", "3 July 1996 (USA)\n"], "bintang": ["Roland Emmerich", "Dean Devlin", "Roland Emmerich", "Will Smith", "Bill Pullman", "Jeff Goldblum", "See full cast & crew"], "certificate": "PG-13", "storyline": "The aliens are coming and their goal is to invade and destroy Earth. Fighting superior technology, mankind's best weapon is the will to survive."}
{"judul": "Kingdom of Heaven", "genre": ["Action", "Adventure", "Drama", "6 May 2005 (USA)\n"], "bintang": ["Ridley Scott", "William Monahan", "Orlando Bloom", "Eva Green", "Liam Neeson", "See full cast & crew"], "certificate": "R", "storyline": "Balian of Ibelin travels to Jerusalem during the Crusades of the 12th century, and there he finds himself as the defender of the city and its people."}
{"judul": "Three Billboards Outside Ebbing, Missouri", "genre": ["Comedy", "Crime", "Drama", "1 December 2017 (USA)\n"], "bintang": ["Martin McDonagh", "Martin McDonagh", "Frances McDormand", "Woody Harrelson", "Sam Rockwell", "See full cast & crew"], "certificate": "R", "storyline": "A mother personally challenges the local authorities to solve her daughter's murder when they fail to catch the culprit."}
{"judul": "Baby Driver", "genre": ["Action", "Crime", "Drama", "28 June 2017 (USA)\n"], "bintang": ["Edgar Wright", "Edgar Wright", "Ansel Elgort", "Jon Bernthal", "Jon Hamm", "See full cast & crew"], "certificate": "R", "storyline": "After being coerced into working for a crime boss, a young getaway driver finds himself taking part in a heist doomed to fail."}
{"judul": "Tropic Thunder", "genre": ["Action", "Comedy", "War", "13 August 2008 (USA)\n"], "bintang": ["Ben Stiller", "Justin Theroux", "Ben Stiller", "3 more credits", "Ben Stiller", "Jack Black", "Robert Downey Jr.", "See full cast & crew"], "certificate": "R", "storyline": "Through a series of freak occurrences, a group of actors shooting a big-budget war movie are forced to become the soldiers they are portraying."}
{"judul": "Kingsman: The Secret Service", "genre": ["Action", "Adventure", "Comedy", "13 February 2015 (USA)\n"], "bintang": ["Matthew Vaughn", "Jane Goldman", "Matthew Vaughn", "2 more credits", "Colin Firth", "Taron Egerton", "Samuel L. Jackson", "See full cast & crew"], "certificate": "R", "storyline": "A spy organisation recruits a promising street kid into the agency's training program, while a global threat emerges from a twisted tech genius."}
{"judul": "X-Men: Apocalypse", "genre": ["Action", "Adventure", "Sci-Fi", "27 May 2016 (USA)\n"], "bintang": ["Bryan Singer", "Simon Kinberg", "Bryan Singer", "3 more credits", "James McAvoy", "Michael Fassbender", "Jennifer Lawrence", "See full cast & crew"], "certificate": "PG-13", "storyline": "In the 1980s the X-Men must defeat an ancient all-powerful mutant, En Sabah Nur, who intends to thrive through bringing destruction to the world."}
{"judul": "Point Break", "genre": ["Action", "Crime", "Thriller", "12 July 1991 (USA)\n"], "bintang": ["Kathryn Bigelow", "Rick King", "W. Peter Iliff", "1 more credit", "Patrick Swayze", "Keanu Reeves", "Gary Busey", "See full cast & crew"], "certificate": "R", "storyline": "An F.B.I. Agent goes undercover to catch a gang of surfers who may be bank robbers."}
{"judul": "Aliens", "genre": ["Action", "Adventure", "Sci-Fi", "18 July 1986 (USA)\n"], "bintang": ["James Cameron", "James Cameron", "David Giler", "4 more credits", "Sigourney Weaver", "Michael Biehn", "Carrie Henn", "See full cast & crew"], "certificate": "R", "storyline": "Fifty-seven years after surviving an apocalyptic attack aboard her space vessel by merciless space creatures, Officer Ripley awakens from hyper-sleep and tries to warn anyone who will listen about the predators."}
{"judul": "Dodgeball: A True Underdog Story", "genre": ["Comedy", "Sport", "18 June 2004 (USA)\n"], "bintang": ["Rawson Marshall Thurber", "Rawson Marshall Thurber", "Ben Stiller", "Christine Taylor", "Vince Vaughn", "See full cast & crew"], "certificate": "PG-13", "storyline": "A group of misfits enter a Las Vegas dodgeball tournament in order to save their cherished local gym from the onslaught of a corporate health fitness chain."}
{"judul": "Bohemian Rhapsody", "genre": ["Biography", "Drama", "Music", "2 November 2018 (USA)\n"], "bintang": ["Bryan Singer", "Anthony McCarten", "Peter Morgan", "1 more credit", "Rami Malek", "Lucy Boynton", "Gwilym Lee", "See full cast & crew"], "certificate": "PG-13", "storyline": "The story of the legendary British rock band "}
{"judul": "The Princess Bride", "genre": ["Adventure", "Family", "Fantasy", "9 October 1987 (USA)\n"], "bintang": ["Rob Reiner", "William Goldman", "William Goldman", "Cary Elwes", "Mandy Patinkin", "Robin Wright", "See full cast & crew"], "certificate": "PG", "storyline": "While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles, enemies and allies in his quest to be reunited with his true love."}
{"judul": "Ready Player One", "genre": ["Action", "Adventure", "Sci-Fi", "29 March 2018 (USA)\n"], "bintang": ["Steven Spielberg", "Zak Penn", "Ernest Cline", "1 more credit", "Tye Sheridan", "Olivia Cooke", "Ben Mendelsohn", "See full cast & crew"], "certificate": "PG-13", "storyline": "When the creator of a virtual reality called the OASIS dies, he makes a posthumous challenge to all OASIS users to find his Easter Egg, which will give the finder his fortune and control of his world."}
{"judul": "Miss Peregrine's Home for Peculiar Children", "genre": ["Adventure", "Drama", "Family", "30 September 2016 (USA)\n"], "bintang": ["Tim Burton", "Ransom Riggs", "Jane Goldman", "Eva Green", "Asa Butterfield", "Samuel L. Jackson", "See full cast & crew"], "certificate": "PG-13", "storyline": "When Jacob (Asa Butterfield) discovers clues to a mystery that stretches across time, he finds Miss Peregrine's Home for Peculiar Children. But the danger deepens after he gets to know the residents and learns about their special powers."}
{"judul": "Ford v Ferrari", "genre": ["Action", "Biography", "Drama", "15 November 2019 (USA)\n"], "bintang": ["James Mangold", "Jez Butterworth", "John-Henry Butterworth", "1 more credit", "Matt Damon", "Christian Bale", "Jon Bernthal", "See full cast & crew"], "certificate": "PG-13", "storyline": "American car designer "}
{"judul": "The Grand Budapest Hotel", "genre": ["Adventure", "Comedy", "Crime", "28 March 2014 (USA)\n"], "bintang": ["Wes Anderson", "Stefan Zweig", "Wes Anderson", "2 more credits", "Ralph Fiennes", "F. Murray Abraham", "Mathieu Amalric", "See full cast & crew"], "certificate": "R", "storyline": "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge."}
{"judul": "Fight Club", "genre": ["Drama", "15 October 1999 (USA)\n"], "bintang": ["David Fincher", "Chuck Palahniuk", "Jim Uhls", "Brad Pitt", "Edward Norton", "Meat Loaf", "See full cast & crew"], "certificate": "R", "storyline": "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more."}
{"judul": "Speed", "genre": ["Action", "Adventure", "Thriller", "10 June 1994 (USA)\n"], "bintang": ["Jan de Bont", "Graham Yost", "Keanu Reeves", "Dennis Hopper", "Sandra Bullock", "See full cast & crew"], "certificate": "R", "storyline": "A young police officer must prevent a bomb exploding aboard a city bus by keeping its speed above 50 mph."}
{"judul": "Juno", "genre": ["Comedy", "Drama", "25 December 2007 (USA)\n"], "bintang": ["Jason Reitman", "Diablo Cody", "Elliot Page", "Michael Cera", "Jennifer Garner", "See full cast & crew"], "certificate": "PG-13", "storyline": "Faced with an unplanned pregnancy, an offbeat young woman makes an unusual decision regarding the unborn child."}
{"judul": "Alita: Battle Angel", "genre": ["Action", "Adventure", "Sci-Fi", "14 February 2019 (USA)\n"], "bintang": ["Robert Rodriguez", "James Cameron", "Laeta Kalogridis", "1 more credit", "Rosa Salazar", "Christoph Waltz", "Jennifer Connelly", "See full cast & crew"], "certificate": "PG-13", "storyline": "A deactivated cyborg's revived, but can't remember anything of her past and goes on a quest to find out who she is."}
{"judul": "Deadpool", "genre": ["Action", "Adventure", "Comedy", "12 February 2016 (USA)\n"], "bintang": ["Tim Miller", "Rhett Reese", "Paul Wernick", "Ryan Reynolds", "Morena Baccarin", "T.J. Miller", "See full cast & crew"], "certificate": "R", "storyline": "A wisecracking mercenary gets experimented on and becomes immortal but ugly, and sets out to track down the man who ruined his looks."}
{"judul": "The Greatest Showman", "genre": ["Biography", "Drama", "Musical", "20 December 2017 (USA)\n"], "bintang": ["Michael Gracey", "Jenny Bicks", "Bill Condon", "1 more credit", "Hugh Jackman", "Michelle Williams", "Zac Efron", "See full cast & crew"], "certificate": "PG", "storyline": "Celebrates the birth of show business and tells of a visionary who rose from nothing to create a spectacle that became a worldwide sensation."}
{"judul": "Mad Max: Fury Road", "genre": ["Action", "Adventure", "Sci-Fi", "15 May 2015 (USA)\n"], "bintang": ["George Miller", "George Miller", "Brendan McCarthy", "1 more credit", "Tom Hardy", "Charlize Theron", "Nicholas Hoult", "See full cast & crew"], "certificate": "R", "storyline": "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max."}
{"judul": "Deadpool 2", "genre": ["Action", "Adventure", "Comedy", "18 May 2018 (USA)\n"], "bintang": ["David Leitch", "Rhett Reese", "Paul Wernick", "1 more credit", "Ryan Reynolds", "Josh Brolin", "Morena Baccarin", "See full cast & crew"], "certificate": "R", "storyline": "Foul-mouthed mutant mercenary Wade Wilson (a.k.a. Deadpool), brings together a team of fellow mutant rogues to protect a young boy with supernatural abilities from the brutal, time-traveling cyborg Cable."}
{"judul": "The Martian", "genre": ["Adventure", "Drama", "Sci-Fi", "2 October 2015 (USA)\n"], "bintang": ["Ridley Scott", "Drew Goddard", "Andy Weir", "Matt Damon", "Jessica Chastain", "Kristen Wiig", "See full cast & crew"], "certificate": "PG-13", "storyline": "An astronaut becomes stranded on Mars after his team assume him dead, and must rely on his ingenuity to find a way to signal to Earth that he is alive."}
{"judul": "Jojo Rabbit", "genre": ["Comedy", "Drama", "War", "8 November 2019 (USA)\n"], "bintang": ["Taika Waititi", "Christine Leunens", "Taika Waititi", "Roman Griffin Davis", "Thomasin McKenzie", "Scarlett Johansson", "See full cast & crew"], "certificate": "PG-13", "storyline": "A young boy in Hitler's army finds out his mother is hiding a Jewish girl in their home."}
{"judul": "Gone Girl", "genre": ["Drama", "Mystery", "Thriller", "3 October 2014 (USA)\n"], "bintang": ["David Fincher", "Gillian Flynn", "Gillian Flynn", "Ben Affleck", "Rosamund Pike", "Neil Patrick Harris", "See full cast & crew"], "certificate": "R", "storyline": "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent."}
{"judul": "Titanic", "genre": ["Drama", "Romance", "19 December 1997 (USA)\n"], "bintang": ["James Cameron", "James Cameron", "Leonardo DiCaprio", "Kate Winslet", "Billy Zane", "See full cast & crew"], "certificate": "PG-13", "storyline": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic."}
{"judul": "Captain Marvel", "genre": ["Action", "Adventure", "Sci-Fi", "8 March 2019 (USA)\n"], "bintang": ["Anna Boden", "Ryan Fleck", "Anna Boden", "Ryan Fleck", "6 more credits", "Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "See full cast & crew"], "certificate": "PG-13", "storyline": "Carol Danvers becomes one of the universe's most powerful heroes when Earth is caught in the middle of a galactic war between two alien races."}
{"judul": "Avatar", "genre": ["Action", "Adventure", "Fantasy", "18 December 2009 (USA)\n"], "bintang": ["James Cameron", "James Cameron", "Sam Worthington", "Zoe Saldana", "Sigourney Weaver", "See full cast & crew"], "certificate": "PG-13", "storyline": "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home."}
{"judul": "Watchmen", "genre": ["Action", "Drama", "Mystery", "6 March 2009 (USA)\n"], "bintang": ["Zack Snyder", "David Hayter", "Alex Tse", "1 more credit", "Jackie Earle Haley", "Patrick Wilson", "Carla Gugino", "See full cast & crew"], "certificate": "R", "storyline": "In 1985 where former superheroes exist, the murder of a colleague sends active vigilante Rorschach into his own sprawling investigation, uncovering something that could completely change the course of history as we know it."}
{"judul": "Buffy the Vampire Slayer            ", "genre": ["Action", "Drama", "Fantasy", "TV Series (1997\u20132003)\n"], "bintang": ["Joss Whedon", "Sarah Michelle Gellar", "Nicholas Brendon", "Alyson Hannigan", "See full cast & crew"], "certificate": "TV-14", "storyline": "A young woman, destined to slay vampires, demons and other infernal creatures, deals with her life fighting evil, with the help of her friends."}
{"judul": "Alien", "genre": ["Horror", "Sci-Fi", "22 June 1979 (USA)\n"], "bintang": ["Ridley Scott", "Dan O'Bannon", "Dan O'Bannon", "1 more credit", "Sigourney Weaver", "Tom Skerritt", "John Hurt", "See full cast & crew"], "certificate": "R", "storyline": "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun."}
{"judul": "American Horror Story            ", "genre": ["Drama", "Horror", "Thriller", "TV Series (2011\u2013 )\n"], "bintang": ["Brad Falchuk", "Ryan Murphy", "Lady Gaga", "Kathy Bates", "Angela Bassett", "See full cast & crew"], "certificate": "TV-MA", "storyline": "An anthology series centering on different characters and locations, including a house with a murderous past, an insane asylum, a witch coven, a freak show circus, a haunted hotel, a possessed farmhouse, a cult, the apocalypse, and a slasher summer camp."}
{"judul": "Bones            ", "genre": ["Comedy", "Crime", "Drama", "TV Series (2005\u20132017)\n"], "bintang": ["Hart Hanson", "Emily Deschanel", "David Boreanaz", "Michaela Conlin", "See full cast & crew"], "certificate": "TV-14", "storyline": "Forensic anthropologist Dr. Temperance \"Bones\" Brennan and cocky F.B.I. Special Agent Seeley Booth build a team to investigate murders. Quite often, there isn't more to examine than rotten flesh or mere bones."}
{"judul": "The Simpsons            ", "genre": ["Animation", "Comedy", "TV Series (1989\u2013 )\n"], "bintang": ["James L. Brooks", "Matt Groening", "Sam Simon", "Dan Castellaneta", "Nancy Cartwright", "Harry Shearer", "See full cast & crew"], "certificate": "TV-PG", "storyline": "The satiric adventures of a working-class family in the misfit city of Springfield."}
